name: Deploy Grocery App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.vishnuk08 }}
          password: ${{ secrets.dckr_pat_Yu7vLH1Zozl0cktzKJDo6szV5xw }}

      - name: Build Backend
        run: docker build -t vishnuk08/backend:latest ./backend

      - name: Build Frontend
        run: docker build -t vishnuk08/frontend:latest ./frontend

      - name: Push Images
        run: |
          docker push vishnuk08/backend:latest
          docker push vishnuk08/frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.54.166.94.50 }}
          username: ${{ secrets.ubuntu }}
          key: ${{ secrets.MIIEpAIBAAKCAQEAtqSMd9KNlIkWOofaULzJZFXZZ8MscC1z1jqEMDZyVAieLpuQ
1a5xSOLoNObljm5hn08Wt/XlDnbS6CGRfldj6YUK2ct3OEQz2ErNytTIso2AFl6B
860X2brPAX6nRTFW6sJU0OZfg5RXi85mc+6cXRaszhHIOaM7WGqRdzlYzXcaGdW4
jCKlVZm1wZNSOtm+6YlOklOjYbqhse178LGrc37jGCd7U+rsQ0ulAVTB5NfyvyVi
J1iAOAMguvoGlhKLko3rwmjibJMkFgZWKLiLPLIEZeACQrW/+BJCg6x44yqap7s6
N4AIS2ZooRSLtkIaWl7iJPQVYJsLMtc8JyMeVwIDAQABAoIBAQCwOBNPiNcReTL5
Rhpdy8iEBlC8zJMTqMca61qfKeklKytzzKTxhl3G9ScV47GYuud1zdkdpSJb0kmr
rreyLp83sCXH/YgJwcRD6+iiyqrZm6z56DV55ogciyEvUAQTvocd+mHbLGr7iSTu
vzYapR44sqgIKyAEfHnF1QyE+8+ybJQtmMLt7LzMuV7/mKgGnnA96BDGW3KEUDOa
nyb9QROrk/xTDi3z2ZYSQ9l3jZ7QK6cskBGMxMOjIDeT2FGZc0yVeR2gdJVGVWRL
90B9bk5Xa0+KA4dkK76dEoMhZ0miXyL9lRP1zJAVar6gJL8KrJDsIDKPLcHyUzbS
1TOVzjABAoGBAPBEUx/Zfn618kJOyyQ+xxvndI7NToV3bimGnVxNE2tVow/+Zwq3
7nTPTaiYXWohEXntPGDZvGxMhZcIW8ItkncML6wZECd+vEe+DZWqaSNtsl5zOtYu
r3/Y0GjbK0BI1yZp/Yi/xtvQC+DdvF+H2ZcAQHep0Rg8nOgc5ygPU9gZAoGBAMKa
QFO/Z1iogOz/xW2ZU3N580O6N6wJo9Jsyqz/cJQleK7tJHO13dn/B2VeLzhKupaE
/Xt8awor3QqF/LDGBNlplX2+hRRXpGvBUVEfSWX4va0/AVg5pbiSfdVNYrsnonXw
TKaKgbNXGWmpjKVAoOMfXHpanf8VZZ07M2vBxzfvAoGBAIapFJmmMYJdAWFufeZb
lQarq6UZpmehb0mw2+NOg5LF1XVyVVgpjGlFgrX6Z2jDDeNzNkLl5fggz0K9+YeU
OSGl39Yp2eb43herijuW3gRwR+ct2A0Q72XNI8mRBOWrrYInJ2UMbyzlprKqNBiq
sCY0iu1GbR2TYzGoeVn3dTuJAoGAaNqULovDM5IXZZuq1RL4VBAxcxyzQo8vJgJY
cj5wemJ2VEqSiYZEs2EmqwfEiaA6ST//FLpFMoXP5Auty9Hmav7o/YfaTMusXCMd
nYguFDOif+ai4tas5HaKNpQrzovcjY+cvV+D4w3bM4OXtLLN/ZK4UXTiDL+KsN1l
J3qRzSECgYAy1oJgSCTZrr6vBw/2Yftr6ka7mNPXdZPYXrPDDlX1CbwTHn7ijtdg
xjvVBqswoYMJ6fQ5lq0AYkck9Gh66hZyHLNI5ZAuBEqvFV+tVkmUH0E7Z+sKz1Gb
aJqQhVEJrU/dLVJCRD0EDQIoSGqsipXLCcU1NkdvW08d45yNOWga1Q== }}
          script: |
            sudo kubectl rollout restart deployment backend
            sudo kubectl rollout restart deployment frontend
